server:
  port: 21000
eureka:
  instance:
    hostname: localhost

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka.instance.hostname: {eureka.instance.hostname}:eureka.instance.hostname:{server.port}/eureka/